# Generated by Django 4.0.1 on 2022-01-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_usermodel_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='zip_code',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='card',
            field=models.CharField(max_length=16),
        ),
    ]
