# Generated by Django 4.0.1 on 2022-01-10 15:15

import configuration.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='number',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=100, validators=[configuration.validators.PhoneValidator()]),
        ),
    ]
