# Generated by Django 4.0.1 on 2022-01-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productmodel_number_alter_productmodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='name',
            new_name='number',
        ),
    ]
