# Generated by Django 4.0.1 on 2022-01-28 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_name_productmodel_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='count',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='img',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='price',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name=django.core.validators.EmailValidator),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='username',
            field=models.CharField(default=None, max_length=50, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(50)]),
            preserve_default=False,
        ),
    ]
