# Generated by Django 4.0.1 on 2022-01-28 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productmodel_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
